#PATH
db_path = "C:\\Users\\HONOR\\source\\repos\\proekttt\\system-development\\AutomaticSender_PSU\\employees.db"
photo_path = "C:\\Users\\HONOR\\source\\repos\\proekttt\\system-development\\photos"
#SMTP
smtp_username = "b1971ss@mail.ru"
smtp_password = "pUdQrE3evHbRGNctUwq1"
smtp_server = "smtp://smtp.mail.ru:587"
mail_from = "b1971ss@mail.ru"
#HTML
message_subject = "Не забудьте поздравить коллег!"
today_one = <html><body><h1>С Днём Рождения!</h1><p>Сегодня, {date}, празднует День рождения наш сотрудник {names}. Не забудьте его поздравить! </p></body></html>
today_many = <html><body><h1>С Днём Рождения!</h1><p>Сегодня, {date}, празднуют День рождения следующие сотрудники: {names}. Не забудьте их поздравить! </p></body></html>
weekend_one = <html><body><h1>С прошедшим Днём Рождения!</h1><p>В выходные, {date}, праздновал День рождения наш сотрудник {names}. Не забудьте поздравить его с прошедшим праздником! </p></body></html>
weekend_many = <html><body><h1>С прошедшим Днём Рождения!</h1><p>В выходные, {date}, праздновали День рождения следующие сотрудники: {names}. Не забудьте поздравить их с прошедшим праздником! </p></body></html>
    